spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:mapbefine;MODE=MySQL
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  # 프로젝트 파일에서는 실제 EC2 경로
  file:
    path: ./log

